name: livine
description: A Healthcare and Food planner App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 8.5.0+23

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  concentric_transition: ^1.0.3
  font_awesome_flutter: ^10.2.1
  http: ^0.13.5
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.6
  hooks_riverpod: ^2.0.2
  flutter_svg: ^1.1.6
  window_manager: ^0.2.7
  flutter_local_notifications: ^12.0.3
  flutter_native_timezone: ^2.0.0
  connectivity_plus: ^3.0.2
  cached_network_image: ^3.2.2
  freezed_annotation: ^2.2.0
  google_mobile_ads: ^2.2.0
  responsive_framework: ^0.2.0  
  go_router: ^5.1.1
  easy_localization: ^3.0.1
  pay: ^1.0.11
  webview_flutter: ^3.0.4
  lottie: ^1.4.3
  tflite: ^1.1.1
  image_picker: ^0.8.6
  image_cropper: ^3.0.0
  animations: ^2.0.7
  flutter_html: ^3.0.0-alpha.5
  iconsax: ^0.0.8
  json_annotation: ^4.7.0
  device_preview: ^1.1.0
  flutter_switch: ^0.3.2
  google_fonts: ^3.0.1
  fluentui_icons: ^1.0.0
  flutter_hooks: ^0.18.5+1
  riverpod_generator: ^1.0.4
  infinite_scroll_pagination: ^3.2.0
  device_info_plus: ^8.0.0



dev_dependencies:
  json_serializable: ^6.5.4
  flutter_launcher_icons: "^0.10.0"
  flutter_native_splash: ^2.2.12
  build_runner: ^2.3.2
  freezed: ^2.2.1
  flutter_lints: ^2.0.1
  msix: ^3.6.6

  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


msix_config:
  display_name: Livine
  publisher_display_name: Mazen Omar
  identity_name: 4882MazenOmar.Livine
  msix_version: 1.0.1.0
  publisher: CN=02970061-64BA-42D9-9C4F-DFB9B063C27D
  logo_path: C:\Users\orang\Desktop\wa.png
  capabilities: internetClient
  store: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/loading/
    - assets/images/welcome/
    - assets/images/windows/
    - assets/images/onboarding/
    - assets/images/recipes/
    - assets/images/icon/
    - assets/images/icons/
    - assets/images/network/
    - assets/images/profile/
    - assets/images/difficulty/
    - assets/translations/
    - assets/model/




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Kine
      fonts:
        - asset: assets/fonts/kinetika-black.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
