name: livine
description: A Healthcare and Food planner App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 9.0.0+28

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  introduction_screen: ^3.1.12
  http: ^1.1.0
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14
  hooks_riverpod: ^2.4.0
  flutter_svg: ^2.0.7
  flutter_local_notifications: ^14.1.3
  connectivity_plus: ^4.0.2
  cached_network_image: ^3.2.3
  freezed_annotation: ^2.4.1
  responsive_framework: ^1.1.1  
  go_router: ^11.0.0
  webview_flutter: ^4.2.4
  animations: ^2.0.8
  flutter_html: ^3.0.0-alpha.6
  json_annotation: ^4.8.1
  flutter_hooks: ^0.20.1
  infinite_scroll_pagination: ^4.0.0
  device_info_plus: ^9.0.3
  package_info_plus: ^4.1.0
  custom_sliding_segmented_control: ^1.7.5
  dynamic_color: ^1.6.7
  gradient_borders: ^1.0.0
  intl: ^0.18.1
  sliding_up_panel2: ^3.3.0+1
  percent_indicator: ^4.2.3
  share_plus: ^7.1.0
  path_provider: ^2.1.1
  screenshot: ^2.1.0


dev_dependencies:
  analyzer: ^6.2.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  flutter_native_splash: ^2.3.2
  freezed: ^2.4.2
  flutter_lints: ^2.0.3
  riverpod_generator: ^2.3.2
  device_preview: ^1.1.0

  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/loading/
    - assets/images/welcome/
    - assets/images/onboarding/
    - assets/images/recipes/
    - assets/images/icon/
    - assets/images/icons/
    - assets/images/network/
    - assets/images/profile/
    - shorebird.yaml




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Kine
      fonts:
        - asset: assets/fonts/kinetika-black.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
