name: livine
description: A Healthcare and Food planner App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 9.3.5+29

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  hooks_riverpod: ^2.4.9
  flutter_svg: ^2.0.9
  flutter_local_notifications: ^16.2.0
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.3.0
  freezed_annotation: ^2.4.1
  responsive_framework: ^1.1.1  
  go_router: ^12.1.3
  webview_flutter: ^4.4.2
  animations: ^2.0.10
  flutter_html: ^3.0.0-alpha.6
  json_annotation: ^4.8.1
  flutter_hooks: ^0.20.3
  infinite_scroll_pagination: ^4.0.0
  device_info_plus: ^9.1.1
  package_info_plus: ^5.0.1
  custom_sliding_segmented_control: ^1.8.1
  dynamic_color: ^1.6.8
  gradient_borders: ^1.0.0
  intl: ^0.18.0
  sliding_up_panel2: ^3.3.0+1
  percent_indicator: ^4.2.3
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  screenshot: ^2.1.0
  window_manager: ^0.3.7
  github: ^9.20.0
  sentry_flutter: ^7.13.2
  discord_rpc: ^0.0.2
  file_picker: ^6.1.1
  syncfusion_flutter_calendar: ^23.2.6
  auto_size_text: ^3.0.0
  fluentui_system_icons: ^1.1.222
  lottie: ^2.7.0


dev_dependencies:
  analyzer: ^6.2.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  flutter_native_splash: ^2.3.8
  freezed: ^2.4.6
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.9
  device_preview: ^1.1.0
  msix: ^3.16.7
  win32_registry: ^1.1.2
  flutter_dotenv: ^5.1.0

  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

msix_config:
  display_name: Livine
  publisher_display_name: Mazen Omar
  identity_name: 4882MazenOmar.Livine
  msix_version: 2.0.0.0
  publisher: CN=02970061-64BA-42D9-9C4F-DFB9B063C27D
  logo_path: E:\Projects\Livine\livine\assets\images\icon\windows.png
  capabilities: internetClient
  store: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/loading/
    - assets/images/welcome/
    - assets/images/onboarding/
    - assets/images/recipes/
    - assets/images/icon/
    - assets/images/icons/
    - assets/images/network/
    - assets/images/profile/
    - assets/images/windows/
    - shorebird.yaml
    - .env




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Kine
      fonts:
        - asset: assets/fonts/kinetika-black.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
