name: livine
description: A Healthcare and Food planner App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 7.0.0+18

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  concentric_transition: ^1.0.3
  font_awesome_flutter: ^10.1.0
  http: ^0.13.4
  shared_preferences: ^2.0.15
  url_launcher: ^6.0.2
  flutter_riverpod: ^2.0.0-dev.9
  flutter_svg: ^1.1.1+1
  window_manager: ^0.2.5
  auto_updater: ^0.1.5
  rive: ^0.9.0
  flutter_local_notifications: ^9.7.0
  flutter_native_timezone: ^2.0.0
  flutter_email_sender: ^5.1.0
  connectivity_plus: ^2.3.5
  cached_network_image: ^3.2.1
  freezed_annotation: ^2.0.3
  google_mobile_ads: ^1.3.0
  responsive_framework: ^0.2.0  
  go_router: ^4.1.0
  easy_localization: ^3.0.1
  new_version: ^0.3.1
  webview_flutter: ^3.0.4
  liquid_pull_to_refresh: ^3.0.1
  lottie: ^1.3.0
  tflite: ^1.1.2
  image_picker: ^0.8.5+3
  image_cropper: ^2.0.3
  intl: ^0.17.0
  percent_indicator: ^4.2.2



dev_dependencies:
  json_serializable: ^6.3.1
  flutter_launcher_icons: "^0.9.3"
  flutter_native_splash: ^2.2.4
  build_runner: ^2.2.0
  freezed: ^2.0.5
  flutter_lints: ^2.0.1

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/rive/
    - assets/images/loading/
    - assets/images/onboarding/
    - assets/images/recipes/
    - assets/images/icon/
    - assets/images/icons/
    - assets/images/calories/breakfast/
    - assets/images/calories/dinner/
    - assets/images/calories/snacks/
    - assets/images/calories/lunch/
    - assets/images/network/
    - assets/images/profile/
    - assets/images/difficulty/
    - assets/translations/
    - assets/model/
    - assets/notifications/




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: BalooBhaina
      fonts:
        - asset: assets/fonts/BalooBhaina2-Regular.ttf
    - family: Kine
      fonts:
        - asset: assets/fonts/kinetika-black.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
