name: Build APK

on:
  workflow_call:
    inputs:
      version:
        description: "Version"
        required: true
        default: "0.0.0"
        type: string
      release-upload-url:
        description: "Release upload URL"
        required: true
        type: string
      app-name:
        description: "Application name"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RELEASE_PATH: build/app/outputs/apk/release
      APPNAME: ${{ inputs.app-name }}
      VERSION: ${{ inputs.version }}
    steps:
        - name: Checkout the code
          uses: actions/checkout@v3
        - uses: actions/setup-java@v2
          with:
            distribution: 'zulu'
            java-version: '11'

        - name: Remove Windows Assets
          run: / 
            cd ./assets/ && rm -r windows

        - name: Remove Windows Packages
          run: /
            sed -i '/fluentui_system_icons/d' pubspec.yaml

        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
            

        - name: Create .env file
          run: |
            cat > .env <<EOF
            DISCORDAPPID=${{ secrets.DISCORDAPPID }}
            SENTRYDSN=${{ secrets.SENTRYDSN }}
            UPDATE=true
            EOF
              
        - name: Building APKs
          run: flutter build apk --split-per-abi --obfuscate --split-debug-info=./debug

        - name: List Directory Contents
          run: ls -R ${{ env.RELEASE_PATH }}

        - name: Upload APKs to release
          uses: softprops/action-gh-release@v1
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: |
              ${{ env.RELEASE_PATH }}/*.apk

          # env:
          #   GITHUB_TOKEN: ${{ github.token }}
          # with:
          #   upload_url: ${{ inputs.release-upload-url }}
          #   asset_path: ${{ env.RELEASE_PATH }}/*.apk
          #   asset_name: |
          #     ${{ env.APPNAME }}-armeabi-v7a-release.apk
          #     ${{ env.APPNAME }}-arm64-v8a-release.apk
          #     ${{ env.APPNAME }}-x86_64-release.apk

          #   asset_content_type: application/apk





    


