name: Build APK

on:
  workflow_call:
    inputs:
      version:
        description: "Version"
        required: true
        default: "0.0.0"
        type: string
      release-upload-url:
        description: "Release upload URL"
        required: true
        type: string
      app-name:
        description: "Application name"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RELEASE_PATH: build/app/outputs/apk/release
      APPNAME: ${{ inputs.app-name }}
      VERSION: ${{ inputs.version }}
    steps:
        - name: Checkout the code
          uses: actions/checkout@v3
        - uses: actions/setup-java@v2
          with:
            distribution: 'zulu'
            java-version: '11'

        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
    
        - name: Building APKs
          run: flutter build apk --split-per-abi

        - name: List Directory Contents
          run: ls -R ${{ env.RELEASE_PATH }}

        - name: Install hub
          uses: geertvdc/setup-hub@master

        - name: Upload APKs to release
          env:
            GITHUB_TOKEN: ${{ github.token }}
            GITHUB_USER: ${{ secrets.GITHUB_USER }}

          run: |
            tag_name="${GITHUB_REF##*/}"
            hub release edit $(find ./${{ env.RELEASE_PATH }} -type f -name "*.apk" -printf "-a %p ") -m "" "$tag_name"


        - name: Archive Release
          uses: thedoctor0/zip-release@master
          with:
            type: "zip"
            filename: ${{ env.APPNAME }}-android.zip
            directory: ${{ env.RELEASE_PATH }}


        - name: upload zip to release
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ github.token }}
          with:
            upload_url: ${{ inputs.release-upload-url }}
            asset_path: ${{env.RELEASE_PATH}}/${{env.APPNAME}}-android.zip
            asset_name: ${{env.APPNAME}}-android.zip
            asset_content_type: application/zip





    


